
// Objective-C API for talking to the following Go packages
//
//	ioslevis
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ioslevis_FRAMEWORK_H__
#define __Ioslevis_FRAMEWORK_H__

#include "Ioslevis.objc.h"
#include "Universe.objc.h"

#endif
